# Connection to real DynamoDB (and hence queues an Nuxeo), but running locally.
database:
  driverClass: org.h2.Driver
#  url: jdbc:h2:/var/db/oai-harvester-database;JMX=true
  url: jdbc:h2:/tmp/oai-harvester-database;JMX=true
  user: user
  password: password
  validationQuery: SELECT 1
  validationQueryTimeout: 1s
  logValidationErrors: true
  minSize: 2
  maxSize: 32
  maxWaitForConnection: 1s
  checkConnectionOnBorrow: true
  checkConnectionOnConnect: true
  checkConnectionOnReturn: true
  autoCommentsEnabled: false

h2Server:
  jdbcPort: 6767

job:
  batchSize: 15
  minThreads: 100
  maxThreads: 1000
  recordQueueCapacity: 10000
  workQueueCapacity: 1
  offerTimeout: PT1M
  pollTimeout: PT5S

httpClient:
  maxConnections: 2048
  maxConnectionsPerRoute: 256
  connectionRequestTimeout: 10s
  connectionTimeout: 10s
  timeout: 5m
  defaultHeaders:
    from: dev@unizin.org

dynamoDB:
  region: us-west-2
  provisionedReadCapacity: 20
  provisionedWriteCapacity: 20
  increaseCapacityThreshold: 500
  decreaseCapacityThreshold: 50
  maxWriteCapacity: 1200

server:
    applicationConnectors:
      - type: http
        port: 8080
    adminConnectors:
      - type: http
        port: 8081

logging:
  appenders:
    - type: console
      threshold: TRACE
      target: stdout
      logFormat: "%level [%date][%thread][%mdc] %logger: %message %n%rEx"
