database:
  driverClass: org.h2.Driver
  url: jdbc:h2:/tmp/oai-harvester-database
  user: ab
  password: b
  validationQuery: SELECT 1
  validationQueryTimeout: 5ms
  logValidationErrors: true
  minSize: 2
  maxSize: 32
  maxWaitForConnection: 10ms
  checkConnectionOnBorrow: true
  checkConnectionOnConnect: true
  checkConnectionOnReturn: true
  autoCommentsEnabled: false

server:
    applicationConnectors:
      - type: http
        port: 9080
    adminConnectors:
      - type: http
        port: 9081

logging:
  appenders:
    - type: console
      threshold: DEBUG
      target: stdout
