---
- hosts: default
  sudo: yes
  gather_facts: no

  vars:
    - build_js: no

  tasks:
    - name: Build unizin-search JavaScript code
      local_action: command node_modules/.bin/webpack --bail chdir=../unizin-parent/unizin-search/
      sudo: no
      environment:
        NODE_ENV: production
      when: build_js

    - name: Build unizin-ingest JavaScript code
      local_action: command node_modules/.bin/webpack --bail chdir=../unizin-parent/unizin-ingest/
      sudo: no
      environment:
        NODE_ENV: production
      when: build_js

    - name: Copy latest skins to virtual machine
      copy:
        src: ../unizin-parent/{{ item.src }}/target/classes/skin/
        dest: /var/lib/nuxeo/server/nxserver/web/root.war/modules/{{ item.dest }}/skin/
        owner: nuxeo
        group: nuxeo
      with_items:
        - src: unizin-search
          dest: org.unizin.cmp.search
        - src: unizin-ingest
          dest: org.unizin.cmp.ingest
